---
# Satellite Operating System definitions
satellite_operatingsystems:
  - name: 'RedHat'
    major: 8
    minor: 10
    description: 'RedHat 8.10'
    os_family: 'Redhat'
    password_hash: 'SHA256'
    default_templates:
      - template_kind: 'iPXE'
        provisioning_template: 'Kickstart default iPXE'
        state: 'present'

      - template_kind: 'PXELinux'
        provisioning_template: 'Kickstart default PXELinux'
        state: 'present'

      - template_kind: 'provision'
        provisioning_template: 'Kickstart default'
        state: 'present'

      - template_kind: 'finish'
        state: 'absent'

      - template_kind: 'host_init_config'
        provisioning_template: 'Linux host_init_config default'
        state: 'present'

      - template_kind: 'kexec'
        state: 'absent'

      - template_kind: 'PXEGrub'
        state: 'absent'

      - template_kind: 'PXEGrub2'
        state: 'absent'

      - template_kind: 'user_data'
        state: 'absent'

  - name: 'RedHat'
    major: 9
    minor: 6
    description: 'RedHat 9.6'
    os_family: 'Redhat'
    password_hash: 'SHA256'
    default_templates:
      - template_kind: 'iPXE'
        provisioning_template: 'Kickstart default iPXE'
        state: 'present'

      - template_kind: 'PXELinux'
        provisioning_template: 'Kickstart default PXELinux'
        state: 'present'

      - template_kind: 'provision'
        provisioning_template: 'pvt-kickstart_default'
        state: 'present'

      - template_kind: 'finish'
        state: 'absent'

      - template_kind: 'host_init_config'
        provisioning_template: 'Linux host_init_config default'
        state: 'present'

      - template_kind: 'kexec'
        state: 'absent'

      - template_kind: 'PXEGrub'
        state: 'absent'

      - template_kind: 'PXEGrub2'
        provisioning_template: 'pvt-kickstart_default_pxegrub2'
        state: 'present'

      - template_kind: 'user_data'
        state: 'absent'

  - name: 'RedHat'
    major: 10
    minor: 0
    description: 'RedHat 10.0'
    os_family: 'Redhat'
    password_hash: 'SHA256'
    default_templates:
      - template_kind: 'iPXE'
        provisioning_template: 'Kickstart default iPXE'
        state: 'present'

      - template_kind: 'PXELinux'
        provisioning_template: 'Kickstart default PXELinux'
        state: 'present'

      - template_kind: 'provision'
        provisioning_template: 'pvt-kickstart_default'
        state: 'present'

      - template_kind: 'finish'
        state: 'absent'

      - template_kind: 'host_init_config'
        provisioning_template: 'Linux host_init_config default'
        state: 'present'

      - template_kind: 'kexec'
        state: 'absent'

      - template_kind: 'PXEGrub'
        state: 'absent'

      - template_kind: 'PXEGrub2'
        provisioning_template: 'pvt-kickstart_default_pxegrub2'
        state: 'present'

      - template_kind: 'user_data'
        state: 'absent'